"""crear tablas rutas y historial_rutas

Revision ID: 2079f086f642
Revises: 
Create Date: 2026-09-22 18:50:14.737175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2079f086f642'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rutas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('envio_id', sa.UUID(), nullable=False),
    sa.Column('vehiculo_id', sa.UUID(), nullable=True),
    sa.Column('paradas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('distancia_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('hora_estimada_llegada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('veces_recalculada', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rutas_envio_id'), 'rutas', ['envio_id'], unique=False)
    op.create_table('historial_rutas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ruta_id', sa.UUID(), nullable=False),
    sa.Column('paradas_anteriores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('distancia_km_anterior', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('hora_estimada_llegada_anterior', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo_recalculo', sa.Text(), nullable=True),
    sa.Column('recalculado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ruta_id'], ['rutas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_rutas_ruta_id'), 'historial_rutas', ['ruta_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historial_rutas_ruta_id'), table_name='historial_rutas')
    op.drop_table('historial_rutas')
    op.drop_index(op.f('ix_rutas_envio_id'), table_name='rutas')
    op.drop_table('rutas')
    # ### end Alembic commands ###
