"""agregar kilometraje_inicio_ruta a rutas

Revision ID: 7b7f58b8f9ef
Revises: cc603030054d
Create Date: 2026-09-28 13:02:47.787225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b7f58b8f9ef'
down_revision: Union[str, Sequence[str], None] = 'cc603030054d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
