"""agregar kilometraje_inicio_ruta a rutas

Revision ID: cc603030054d
Revises: 2079f086f642
Create Date: 2026-09-28 12:44:59.849925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc603030054d'
down_revision: Union[str, Sequence[str], None] = '2079f086f642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rutas', sa.Column('kilometraje_inicio_ruta', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rutas', 'kilometraje_inicio_ruta')
    # ### end Alembic commands ###
